### ISSUE TITLE
Clarification on the input matrices

### ISSUE THREAD

**Issue by bmill3r** [Su-informatics-lab/DSTG#9]
Hello,

Quick question - can you provide more clarification on the format of the input files? Presumably "scRNAseq_data.RDS" and "spatial_data.RDS" need to be gene x cell or gene x spot count matrices but I am unclear as to what the "scRNAseq_label.RDS" needs to be. Looking at the example demo, this appears to be known proportions of cell-types in the spots, but if using my own data without a ground truth, I am unsure what this file should be.

Additionally, for the demo data, is "example_data.RDS" a list of the scRNA-seq gene count matrix and the ST gene count matrix? What are the different components of the list "example_labels.RDS"?

Thanks in advance

**Comment by QSong-github** [comment]
The "scRNAseq_labels.RDS" refers to the ground truth of single-cell RNA-seq cell labels, so you should have it. 

As for the synthetic data, the "example_data.RDS" a list of the scRNA-seq gene count matrix and the ST gene count matrix. The "example_labels.RDS" is their corresponding labels/compositions. 

Hope this helps.

**Comment by bmill3r** [comment]
Thanks for getting back to me.

I think I'm still a little confused. In the demo data, it looks like `example_data[[1]]` is simulated pseudo mixtures of spots created from scRNA-seq data. `example_data[[2]]` then must be "real" ST data. So in this case, would `example_label[[1]]` be the proportions of the scRNA-seq pseudo mixtures? And `example_label[[2]]` be the ground truth cell-type proportions in the "real" ST data?

When I attempt to use my own data, would `scRNAseq_data.RDS` be pseudo mixtures from scRNA-seq data? I ask because in `convert_data.R` it looks like this is added to the `count.list` in place of the demo `example_data[[1]]`. `spatial_data.RDS` must be my own real ST data. Based on this logic, would `scRNAseq_label.RDS` be the cell-type proportions of the pseudo mixtures I created with my own scRNA-seq data? 

If I use these as the inputs into `convert_data.R`, I am able to create the expected folders in `Infor_Data/`. One caveat is that I need to run the command using: `anova = FALSE` otherwise it tries to generate pseudo mixtures which I have already done. However, I only have the `*_1.csv` files and the `*_2.csv` files I get using the demo data are missing. Because of this, I also cannot run `python train.py` because it is expecting both `_*1.csv` and `*_2.csv` in the subfolders within `Infor_Data/`. 

Is my logic with the input files correct? Or should `scRNAseq_data.RDS` be the actual scRNA-seq data and not pseudo mixtures? If it is supposed to be the actual scRNA-seq data, then how should `scRNAseq_label.RDS` be structured? 

Thank you - let me know if that doesn't make sense.

**Comment by QSong-github** [comment]
> When I attempt to use my own data, would `scRNAseq_data.RDS` be pseudo mixtures from scRNA-seq data? I ask because in `convert_data.R` it looks like this is added to the `count.list` in place of the demo `example_data[[1]]`. `spatial_data.RDS` must be my own real ST data. Based on this logic, would `scRNAseq_label.RDS` be the cell-type proportions of the pseudo mixtures I created with my own scRNA-seq data?
> 

If you use your own data, the "scRNAseq_data.RDS" is not pseudo mixtures. DSTG will create pseudo mixtures based on your input scRNA-seq data. The "scRNAseq_label.RDS" is the corresponding cell types of your scRNA-seq data.

**Comment by bmill3r** [comment]
Sorry to keep bothering you about this but I think there are still a few issues to sort out.

I believe I have the inputs figured out in that `scRNAseq_data.RDS` is now a genes x cell count matrix of scRNA-seq data, `spatial_data.RDS` is now a genes x spot count matrix, and I have `scRNAseq_label.RDS` as a single column data.frame where the rownames are the cell IDs from the scRNA-seq data, and the column values are the cell-type labels for the cells.

With these inputs, `convert_data.R` now runs as:
```
Convert_Data(count.list,label.list,anova=TRUE)
```
but with `anova = TRUE`, `data_process()` fails on line 110 in `R_utils.R`:
```
label.list2 <- do.call("rbind", rep(list(st_labels[[1]]), round(N2/N1)+1))[1:N2]
```
because st_labels has not been defined previously.
```
Error in h(simpleError(msg, call)) : error in evaluating the argument 'args' in selecting a method for function 'do.call': object 'st_labels' not found
```

Note that changing `st_labels` to `st_label` results in a new error:
```
Error in `[.data.frame`(do.call("rbind", rep(list(st_label[[1]]), round(N2/N1) +  : 
  undefined columns selected
```

If I set `anova = FALSE`, `convert_data.R` still fails because it is expecting `label.list` to have 2 entries.
```
for (i in 1:2){
        write.csv(st.count[[i]],file=paste0(inforDir,'/ST_count/ST_count_',i,'.csv'),quote=F)
        write.csv(label.list[[i]],file=paste0(inforDir,'/ST_label/ST_label_',i,'.csv'),quote=F)
        write.csv(st.norm[[i]],file=paste0(inforDir,'/ST_norm/ST_norm_',i,'.csv'),quote=F)
        write.csv(st.scale[[i]],file=paste0(inforDir,'/ST_scale/ST_scale_',i,'.csv'),quote=F)
    }
```
I think because when the demo data is run, the label list has two entries already so this is ok. But with my own data, because I did not generate pseudo mixtures by setting `anova = FALSE`, there was no second entry added.

I tried to change `for (i in 1:2)` to `for (i in 1:1)` and `convert_data.R` now works but expectedly `python train.py` fails because the `*_2.csv` files in the subfolders of `Infor_Data/` are missing, which appear to be required when `Link_Graph()` is called via `input_data()` in `data.py`.

Do you have any suggestions on how to proceed?

Thank you

**Comment by QSong-github** [comment]
Thank you for point it out. It is a typo and I have corrected it accordingly. Would you update the tool and re-run? Let me know if you have further issues.

**Comment by bmill3r** [comment]
Another issue:

`select_feature()` adds an `NA` to the end of the`sel.features` vector in `data_process()` so there is an error about invalid character indexing. Adding the following lines to remove NA's solves this issue:
```
sel.features <- select_feature(st_count[[1]],st_label[[1]])
sel.features <- sel.features[!is.na(sel.features)]
```

Also, the tool still does not run. Changing `st_labels` to `st_label` results in a new error:
```
Error in `[.data.frame`(do.call("rbind", rep(list(st_label[[1]]), round(N2/N1) +  : 
  undefined columns selected
```

The problem here is the indexing of `[1:N2]` on the line: `label.list2 <- do.call("rbind", rep(list(st_label[[1]]), round(N2/N1)+1))[1:N2]`

Looking at the lines in `data_processs()`:
```
st_counts <- list(test.spot.counts1,st_count_new[[2]])
st_label[[1]] <- test.spot.metadata1
N1 <- ncol(st_counts[[1]]); N2 <- ncol(st_counts[[2]])
```
`st_counts` is list, where the first entry is the pseudo-mixture data.frame, with 1000 mixtures as the columns. So my `N1 = 1000`. The second entry is my real ST data, which in my case has 3072 spots, so `N2=3072`.

`st_label` is a list with one entry, which is a data.frame of 1000 simulated mixtures x the cell-types (I have 9 in my case).
`round(N2/N1)+1 = 4`, so `rep(list(st_label[[1]]), round(N2/N1)+1)` is a list with 4 identical data.frames of `st_label`. So `do.call("rbind", rep(list(st_label[[1]]), round(N2/N1)+1))` is now a single data.frame that is 4000 rows x 9 cell-types. So therefore, indexing this as `[1:N2]` doesn't work because it is not a list or vector. I assume this is meant to be rows and thus should be `[1:N2, ]`, but not sure why rows 1 through 3072 are being indexed when rows 1:1000, 1001:2000, and 2001:3000 will be identical sets.

Finally, I noticed one more potential error:
Even if I change `[1:N2]` to `[1:N2,]`, the tool still fails in `Convert_Data()`. This is because I think at the end:
```
for (i in 1:2){
        write.csv(st.count[[i]],file=paste0(inforDir,'/ST_count/ST_count_',i,'.csv'),quote=F)
        write.csv(label.list[[i]],file=paste0(inforDir,'/ST_label/ST_label_',i,'.csv'),quote=F)
        write.csv(st.norm[[i]],file=paste0(inforDir,'/ST_norm/ST_norm_',i,'.csv'),quote=F)
        write.csv(st.scale[[i]],file=paste0(inforDir,'/ST_scale/ST_scale_',i,'.csv'),quote=F)
}
```

`length(label.list) = 1`. This is because it is the original `scRNAseq_labels.RDS`. I think what you might want instead is the `st.label` which is generated at the beginning of this function here:
```
step1 <- data_process(st_count=count.list,st_label=label.list,anova)
st.count <- step1[[1]];
st.label <- step1[[2]];
st.norm <- step1[[3]];
st.scale <- step1[[4]];
variable.genes <- step1[[5]]
```

**Comment by bmill3r** [comment]
After making the changes I indicated above, I get `*_1.csv` and `*_2.csv` files in the subfolders of `Infor_Data/`. 

`python train.py` runs up to:
```
...
True
True
True
load data succesfully....
```
but then fails with the following error:
```
Traceback (most recent call last):
  File "./train.py", line 35, in <module>
    FLAGS.dataset)
  File "./utils.py", line 116, in load_data
    matrix[tuple(id_grp1.T)] = 1
IndexError: too many indices for array
```
maybe this has something to do with the matrices that were generated via `convert_data.R` with the changes I made in `R_utils.R` to get it to run?

**Comment by QSong-github** [comment]
> After making the changes I indicated above, I get `*_1.csv` and `*_2.csv` files in the subfolders of `Infor_Data/`.
> 
> `python train.py` runs up to:
> 
> ```
> ...
> True
> True
> True
> load data succesfully....
> ```
> 
> but then fails with the following error:
> 
> ```
> Traceback (most recent call last):
>   File "./train.py", line 35, in <module>
>     FLAGS.dataset)
>   File "./utils.py", line 116, in load_data
>     matrix[tuple(id_grp1.T)] = 1
> IndexError: too many indices for array
> ```
> 
> maybe this has something to do with the matrices that were generated via `convert_data.R` with the changes I made in `R_utils.R` to get it to run?

The reason for this error should be due to the *.csv files generated from "convert_data.R". You may have extra columns for python input. Please check your .csv files, and make sure it has consistent columns with the files generated from example data.

**Comment by bmill3r** [comment]
Thanks again,

I have confirmed that there are no extra columns in the `*.csv` files and that the structure is the same as those created from the demo data after `convert_data.R`.

The error occurs on line 116 of `utils.py` in the function `load_data()`, where
```
matrix[tuple(id_grp1.T)] = 1
```
It seems that the issue is indexing `matrix` with `tuple(id_grp1.T)`. Digging deeper, `id_grp1` seems to be the issue when comparing the `id_grp1` that is generated when using the `*.csv` files from the demo data versus my own. For example, with the demo data, it looks like:
```
array([[ 810,  810],
       [1264,  816],
       [1240,  825],
       ...,
       [ 950,  813],
       [1293,  836],
       [1359,  811]])
```
and thus `id_grp1.T` is:
```
array([[ 810, 1264, 1240, ...,  950, 1293, 1359],
       [ 810,  816,  825, ...,  813,  836,  811]])
```
and `tuple(id_grp1.T)` is:
```
(array([ 810, 1264, 1240, ...,  950, 1293, 1359]),
 array([810, 816, 825, ..., 813, 836, 811]))
```
whereas the `id_grp1` from my data is:
```
array([array([810, 810]), array([811, 810]), array([811, 810]), ...,
       array([810, 810]), array([810, 810]), array([811, 810])],
      dtype=object)
```
And thus `id_grp1.T` is:
```
array([array([810, 810]), array([811, 810]), array([811, 810]), ...,
       array([810, 810]), array([810, 810]), array([811, 810])],
      dtype=object)
```
and `tuple(id_grp1.T)` is:
```
(array([810, 810]),
 array([811, 810]),
 array([811, 810]),
 array([810, 810]),
...
```
Basically, `id_grp1` is supposed to be a 2-dimensional array but in my case it is a 1-dimensional array of 1x2 arrays.

Digging even deeper, I looked where where `id_grp1` is made:
```
id_grp1 = np.array([
    np.concatenate((np.where(find1 == id_graph2.iloc[i, 1])[0],
                    np.where(find1 == id_graph2.iloc[i, 0])[0]))
    for i in range(len(id_graph2))
])
```
and as it happens, there are instances where `np.where(find1 == id_graph2.iloc[i, 1])` does not match anything, and thus the returned array is 1x1 and not 1x2. 
```
[np.where(find1 == id_graph2.iloc[i, 1])]
```
```
...
array([811]),
 array([810]),
 array([], dtype=int64),
 array([818]),
 array([2351]),
...
```
I noticed that I get a warning:
```
Creating an ndarray from ragged nested sequences...
```
And so looking back to where `id_grp1` is made, it is attempting to make an array out of a list of arrays that are not the same dimension (some are 1x2, others are 1x1 due to nothing matching to `find1`, and thus why I get an array of a list of arrays instead of the 2D array that is needed for proper indexing downstream.

Why there are no matches in some cases I am not sure. The dimensions of the matrices in the demo data are the same between the ST and scRNAseq data, but mine are different. Could this be a reason? It might be happening somewhere in `link_graph()` but it's not clear.

Again, the `*.csv` files I have look the same as the ones generated from the demo except that the dimensions are different and the values are different.

Do you have any other suggestions?

Thank you

**Comment by QSong-github** [comment]
> Thanks again,
> 
> I have confirmed that there are no extra columns in the `*.csv` files and that the structure is the same as those created from the demo data after `convert_data.R`.
> 
> The error occurs on line 116 of `utils.py` in the function `load_data()`, where
> 
> ```
> matrix[tuple(id_grp1.T)] = 1
> ```
> 
> It seems that the issue is indexing `matrix` with `tuple(id_grp1.T)`. Digging deeper, `id_grp1` seems to be the issue when comparing the `id_grp1` that is generated when using the `*.csv` files from the demo data versus my own. For example, with the demo data, it looks like:
> 
> ```
> array([[ 810,  810],
>        [1264,  816],
>        [1240,  825],
>        ...,
>        [ 950,  813],
>        [1293,  836],
>        [1359,  811]])
> ```
> 
> and thus `id_grp1.T` is:
> 
> ```
> array([[ 810, 1264, 1240, ...,  950, 1293, 1359],
>        [ 810,  816,  825, ...,  813,  836,  811]])
> ```
> 
> and `tuple(id_grp1.T)` is:
> 
> ```
> (array([ 810, 1264, 1240, ...,  950, 1293, 1359]),
>  array([810, 816, 825, ..., 813, 836, 811]))
> ```
> 
> whereas the `id_grp1` from my data is:
> 
> ```
> array([array([810, 810]), array([811, 810]), array([811, 810]), ...,
>        array([810, 810]), array([810, 810]), array([811, 810])],
>       dtype=object)
> ```
> 
> And thus `id_grp1.T` is:
> 
> ```
> array([array([810, 810]), array([811, 810]), array([811, 810]), ...,
>        array([810, 810]), array([810, 810]), array([811, 810])],
>       dtype=object)
> ```
> 
> and `tuple(id_grp1.T)` is:
> 
> ```
> (array([810, 810]),
>  array([811, 810]),
>  array([811, 810]),
>  array([810, 810]),
> ...
> ```
> 
> Basically, `id_grp1` is supposed to be a 2-dimensional array but in my case it is a 1-dimensional array of 1x2 arrays.
> 
> Digging even deeper, I looked where where `id_grp1` is made:
> 
> ```
> id_grp1 = np.array([
>     np.concatenate((np.where(find1 == id_graph2.iloc[i, 1])[0],
>                     np.where(find1 == id_graph2.iloc[i, 0])[0]))
>     for i in range(len(id_graph2))
> ])
> ```
> 
> and as it happens, there are instances where `np.where(find1 == id_graph2.iloc[i, 1])` does not match anything, and thus the returned array is 1x1 and not 1x2.
> 
> ```
> [np.where(find1 == id_graph2.iloc[i, 1])]
> ```
> 
> ```
> ...
> array([811]),
>  array([810]),
>  array([], dtype=int64),
>  array([818]),
>  array([2351]),
> ...
> ```
> 
> I noticed that I get a warning:
> 
> ```
> Creating an ndarray from ragged nested sequences...
> ```
> 
> And so looking back to where `id_grp1` is made, it is attempting to make an array out of a list of arrays that are not the same dimension (some are 1x2, others are 1x1 due to nothing matching to `find1`, and thus why I get an array of a list of arrays instead of the 2D array that is needed for proper indexing downstream.
> 
> Why there are no matches in some cases I am not sure. The dimensions of the matrices in the demo data are the same between the ST and scRNAseq data, but mine are different. Could this be a reason? It might be happening somewhere in `link_graph()` but it's not clear.
> 
> Again, the `*.csv` files I have look the same as the ones generated from the demo except that the dimensions are different and the values are different.
> 
> Do you have any other suggestions?
> 
> Thank you

Hi thank you for letting me know. Would you send me your data thus I can further look into it? you can send to my work email: qsong@wakehealth.edu, or shared through google drive to wasqqdyx@gmail.com.

Thanks.

**Comment by bmill3r** [comment]
Thank you for your help - I just sent a link to the files over google drive.

Thanks again

**Comment by QSong-github** [comment]
> Thank you for your help - I just sent a link to the files over google drive.
> 
> Thanks again

Thanks for providing the test data. I have updated the codes, now it should work. Let me know if you still have problems.

**Comment by bmill3r** [comment]
Thank you so much!

There was one small change I had to make to `utils.py` but then it worked.
```
True
True
True
load data succesfully....
Traceback (most recent call last):
  File "./train.py", line 35, in <module>
    FLAGS.dataset)
  File "./utils.py", line 31, in load_data
    datas_tr = scipy.sparse.csr_matrix(datas_train.astype('Float64'))
TypeError: data type 'Float64' not understood
```
In `utils.py` on lines 31 to 33 I changed "Float64" to "float64"

```
 #' convert pandas data frame to csr_matrix format
datas_tr = scipy.sparse.csr_matrix(datas_train.astype('float64'))
datas_va = scipy.sparse.csr_matrix(datas_val.astype('float64'))
datas_te = scipy.sparse.csr_matrix(datas_test.astype('float64'))
```

One last thing and then I think I am all set:
Can you give a little more detail about what the output files `predict_output.csv` and `true_output.csv` contain? I assume that `predict_output.csv` are the cell-type proportions for the pixels in the `spatial_data.RDS`, where rows are pixels and the columns are cell-types, but the columns are unlabeled. What is the order of cell-types for the columns?

Thank you

**Comment by QSong-github** [comment]
> Thank you so much!
> 
> There was one small change I had to make to `utils.py` but then it worked.
> 
> ```
> True
> True
> True
> load data succesfully....
> Traceback (most recent call last):
>   File "./train.py", line 35, in <module>
>     FLAGS.dataset)
>   File "./utils.py", line 31, in load_data
>     datas_tr = scipy.sparse.csr_matrix(datas_train.astype('Float64'))
> TypeError: data type 'Float64' not understood
> ```
> 
> In `utils.py` on lines 31 to 33 I changed "Float64" to "float64"
> 
> ```
>  #' convert pandas data frame to csr_matrix format
> datas_tr = scipy.sparse.csr_matrix(datas_train.astype('float64'))
> datas_va = scipy.sparse.csr_matrix(datas_val.astype('float64'))
> datas_te = scipy.sparse.csr_matrix(datas_test.astype('float64'))
> ```
> 
> One last thing and then I think I am all set:
> Can you give a little more detail about what the output files `predict_output.csv` and `true_output.csv` contain? I assume that `predict_output.csv` are the cell-type proportions for the pixels in the `spatial_data.RDS`, where rows are pixels and the columns are cell-types, but the columns are unlabeled. What is the order of cell-types for the columns?
> 
> Thank you

Yes it may due to different module version if 'Float64' not work. 
The columns of "predict_output.csv" & "true_output.csv" are same with the columns of files in "ST_label" folder. "true_output.csv" should not be considered if using real data, since it is used for validation of simulation data. 
Hope this helps.

**Comment by bmill3r** [comment]
Thank you so much - this was all really helpful. DSTG now works on my end and the results look reasonable. Thanks for your patience and help.
